return {
	"WhoIsSethDaniel/mason-tool-installer.nvim",
	dependencies = { "williamboman/mason.nvim" },
	config = function()
		require("mason-tool-installer").setup({
			ensure_installed = {
				-- LSP servers
				"ltex-ls",
				"pyright",
				"jdtls",
				"java-test",
				"java-debug-adapter",
				"texlab",
				"haskell-language-server",
				"rust-analyzer",
				"lua-language-server",
				"markdown-oxide",
				"tinymist",
				"clangd",
				"bash-language-server",
				"dockerfile-language-server",
				"docker-compose-language-service",
				"bzl",
				"gradle-language-server",
				-- Formatters
				"stylua",
				"black",
				"google-java-format",
				"jq",
				"clang-format",
				"fourmolu",
				"prettier",
				"buildifier",
				"latexindent",
				"bibtex-tidy",
				-- Linters
				"ruff",
				"shellcheck",
				"luacheck",
				"markdownlint",
				"yamllint",
				"mypy",
				"checkstyle",
				"hlint",
				"cpplint",
				-- Debuggers
				"codelldb",
				-- "java-debug-adapter",
				-- "java-test",
			},
			auto_update = false,
			run_on_start = true,
		})
	end,
}
