return {
	lazygit = { enabled = true },
	input = { enabled = true },
	scope = { enabled = true },
	words = { enabled = true },
	scroll = { enabled = true },
	bufdelete = { enabled = true },
	indent = { enabled = true },
	zen = { enabled = true },
	statuscolumn = { enabled = true },
	statusline = { enabled = true },
	dim = { enabled = true },
	git = { enabled = true },
	animate = { enabled = true },
	quickfile = { enabled = true },
	rename = { enabled = true },
	layout = { enabled = true },
	win = { enabled = true },
	bigfile = { enabled = true },
	explorer = { enabled = true },
	scratch = { enabled = true },
	gitbrowse = { enabled = true },
	toggle = { enabled = true },
	debug = { enabled = true },
}

